# -*- mode: python ; coding: utf-8 -*-
#
# argon2-cffi loads its native library at runtime through CFFI's `ffi.dlopen`,
# which means the shared object is not reachable by PyInstaller's import graph.
# `hiddenimports` alone is therefore not enough: the module gets bundled and the
# `.pyd`/`.so` does not, so the frozen build imports cleanly and then raises
# OSError on the first password hash. Collecting the dynamic libraries below is
# what actually fixes it.
from PyInstaller.utils.collectors import collect_dynamic_libs

_argon2_libs = collect_dynamic_libs('argon2_cffi_bindings')
_cffi_libs = collect_dynamic_libs('cffi')

block_cipher = None

a = Analysis(
    ['run_backend.py'],
    pathex=[],
    binaries=_argon2_libs + _cffi_libs,
    datas=[
        ('app', 'app'),
        ('uploads', 'uploads'),
        ('alembic', 'alembic'),
        ('alembic.ini', '.'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.websockets',
        'uvicorn.lifecycle',
        'uvicorn.server',
        'uvicorn.config',
        'uvicorn.main',
        'uvicorn.supervisors',
        'uvicorn.supervisors.basereload',        'uvicorn.supervisors.watchgodreload',
        'uvicorn.supervisors.watchfilesreload',
        'uvicorn.supervisors.multiprocess',
        # argon2-cffi ships a CFFI extension module that PyInstaller's static
        # analysis does not always detect, and a frozen build that cannot
        # import it fails on the *first login* rather than at startup. Listing
        # it explicitly means the failure mode is a build error, not a
        # production incident.
        'argon2',
        'argon2._ffi',
        'argon2.low_level',
        'cffi',
        'cffi.model',
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.responses',
        'fastapi.routing',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.middleware.trustedhost',
        'starlette.responses',
        'starlette.routing',
        'starlette.requests',
        'starlette.datastructures',
        'starlette.background',
        'starlette.concurrency',
        'starlette.types',
        'pydantic',
        'pydantic_core',
        'pydantic_settings',
        'sqlalchemy',
        'sqlalchemy.orm',
        'sqlalchemy.engine',
        'sqlalchemy.pool',
        'sqlalchemy.dialects',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.dialects.postgresql',
        'sqlalchemy.dialects.postgresql.psycopg2',
        'psycopg2',
        'psycopg2._psycopg',
        'psycopg2.extensions',
        'psycopg2.extras',
        'psycopg2.pool',
        'alembic',
        'alembic.config',
        'alembic.script',
        'alembic.migration',
        'alembic.operations',
        'alembic.autogenerate',
        'apscheduler',
        'apscheduler.schedulers',
        'apscheduler.schedulers.background',
        'apscheduler.executors',
        'apscheduler.executors.pool',
        'apscheduler.jobstores',
        'apscheduler.jobstores.memory',
        'apscheduler.triggers',
        'apscheduler.triggers.interval',
        'apscheduler.triggers.cron',
        'apscheduler.triggers.date',
        'apscheduler.util',
        'python_jose',
        'python_jose.jwt',
        'python_jose.jwk',
        'python_jose.jwa',
        'python_jose.exceptions',
        'jwt',
        'jwt.exceptions',
        'jwt.algorithms',
        'pyotp',
        'passlib',
        'passlib.handlers',
        'passlib.handlers.bcrypt',
        'bcrypt',
        'email_validator',
        'requests',
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.units',
        'reportlab.lib.styles',
        'reportlab.lib.enums',
        'reportlab.platypus',
        'reportlab.platypus.tables',
        'reportlab.platypus.flowables',
        'reportlab.pdfbase',
        'reportlab.pdfbase.ttfonts',
        'reportlab.pdfbase.pdfmetrics',
        'arabic_reshaper',
        'bidi',
        'bidi.algorithm',
        'slowapi',
        'slowapi.middleware',
        'slowapi.util',
        'pandas',
        'pandas.core',
        'pandas.io',
        'pandas.io.excel',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.cell',
        'openpyxl.styles',
        'PIL',
        'PIL.Image',
        'PIL.ImageFont',
        'PIL.ImageDraw',
        'decimal',
        'datetime',
        'json',
        'pathlib',
        'os',
        'sys',
        'logging',
        'traceback',
        'asyncio',
        'contextlib',
        'functools',
        'itertools',
        'collections',
        'typing',
        'uuid',
        'hashlib',
        'secrets',
        'string',
        're',
        'time',
        'math',
        'random',
        'fractions',
        'copy',
        'pickle',
        'base64',
        'mimetypes',
        'urllib',
        'urllib.parse',
        'http',
        'http.client',
        'ssl',
        'socket',
        'select',
        'signal',
        'subprocess',
        'threading',
        'multiprocessing',
        'queue',
        'weakref',
        'gc',
        'inspect',
        'importlib',
        'importlib.metadata',
        'importlib.resources',
        'pkgutil',
        'dataclasses',
        'enum',
        'types',
        'numbers',
        'operator',
        'statistics',
        'textwrap',
        'unicodedata',
        'warnings',
        'zoneinfo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon='icon.ico',
)