import {
  LayoutDashboard,
  Users,
  Scissors,
  CalendarDays,
  Receipt,
  ClipboardList,
  Settings,
  UserCircle,
  ShieldCheck,
} from "lucide-react";

export const sidebarMenu = [
  {
    key: "dashboard-owner",
    label: "لوحة المالك",
    to: "/dashboard",
    icon: LayoutDashboard,
    roles: ["owner"],
  },
  {
    key: "dashboard-manager",
    label: "لوحة المدير",
    to: "/manager-dashboard",
    icon: LayoutDashboard,
    roles: ["manager"],
  },
  {
    key: "dashboard-cashier",
    label: "لوحة الكاشير",
    to: "/cashier-dashboard",
    icon: LayoutDashboard,
    roles: ["cashier"],
  },
  {
    key: "dashboard-barber",
    label: "لوحة الحلاق",
    to: "/barber-dashboard",
    icon: LayoutDashboard,
    roles: ["barber"],
  },
  {
    key: "customers",
    label: "العملاء",
    to: "/customers",
    icon: Users,
    roles: ["owner", "manager", "cashier"],
  },
  {
    key: "services",
    label: "الخدمات",
    to: "/services",
    icon: Scissors,
    roles: ["owner", "manager", "cashier"],
  },
  {
    key: "barbers",
    label: "الحلاقين",
    to: "/barbers",
    icon: ShieldCheck,
    roles: ["owner", "manager"],
  },
  {
    key: "appointments",
    label: "الحجوزات",
    to: "/appointments",
    icon: CalendarDays,
    roles: ["owner", "manager", "cashier", "barber"],
  },
  {
    key: "sessions",
    label: "الجلسات",
    to: "/sessions",
    icon: ClipboardList,
    roles: ["owner", "manager", "cashier", "barber"],
  },
  {
    key: "invoices",
    label: "الفواتير",
    to: "/invoices",
    icon: Receipt,
    roles: ["owner", "manager", "cashier"],
  },
  {
    key: "users",
    label: "المستخدمون والصلاحيات",
    to: "/users",
    icon: ShieldCheck,
    roles: ["owner", "manager"],
  },
  {
    key: "business-settings",
    label: "إعدادات المحل",
    to: "/business-settings",
    icon: Settings,
    roles: ["owner", "manager"],
  },
  {
    key: "profile",
    label: "الملف الشخصي",
    to: "/profile",
    icon: UserCircle,
    roles: ["owner", "manager", "cashier", "barber"],
  },
];
