import {
  LayoutDashboard,
  Users,
  Scissors,
  CalendarDays,
  Receipt,
  ClipboardList,
  Settings,
  UserCircle,
  ShieldCheck,
} from "lucide-react";

export const sidebarMenu = [
  {
    key: "dashboard-owner",
    label: "لوحة المالك",
    to: "/owner",
    icon: LayoutDashboard,
    roles: ["owner"],
  },
  {
    key: "dashboard-manager",
    label: "لوحة المدير",
    to: "/manager",
    icon: LayoutDashboard,
    roles: ["manager"],
  },
  {
    key: "dashboard-cashier",
    label: "لوحة الكاشير",
    to: "/cashier",
    icon: LayoutDashboard,
    roles: ["cashier"],
  },
  {
    key: "dashboard-barber",
    label: "لوحة الحلاق",
    to: "/barber",
    icon: LayoutDashboard,
    roles: ["barber"],
  },
  {
    key: "customers",
    label: "العملاء",
    to: "/customers",
    icon: Users,
    roles: ["owner", "manager", "cashier"],
  },
  {
    key: "services",
    label: "الخدمات",
    to: "/owner/services",
    icon: Scissors,
    roles: ["owner"],
  },
  {
    key: "hr",
    label: "الموظفون",
    to: "/owner/hr",
    icon: ShieldCheck,
    roles: ["owner"],
  },
  {
    key: "appointments",
    label: "الحجوزات",
    to: "/bookings",
    icon: CalendarDays,
    roles: ["owner", "manager", "cashier", "barber"],
  },
  {
    key: "reception-board",
    label: "لوحة الاستقبال",
    to: "/reception-board",
    icon: ClipboardList,
    roles: ["owner", "manager", "cashier", "barber"],
  },
  {
    key: "invoices",
    label: "الفواتير",
    to: "/invoices",
    icon: Receipt,
    roles: ["owner", "manager", "cashier"],
  },
  {
    key: "users",
    label: "المستخدمون والصلاحيات",
    to: "/owner/users",
    icon: ShieldCheck,
    roles: ["owner"],
  },
  {
    key: "business-settings",
    label: "إعدادات المحل",
    to: "/owner/business-settings",
    icon: Settings,
    roles: ["owner"],
  },
  {
    key: "profile",
    label: "الملف الشخصي",
    to: "/profile",
    icon: UserCircle,
    roles: ["owner", "manager", "cashier", "barber"],
  },
];
