"""add_invoice_financial_fields

Revision ID: 130a4bf7d47e
Revises: 843771966984
Create Date: 2026-05-27 20:02:13.841536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130a4bf7d47e'
down_revision: Union[str, None] = '843771966984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('subtotal_amount')

    # ### end Alembic commands ###
