"""add status to expenses and commission_amount to invoice_items

Revision ID: 3e00e10485d0
Revises: 4e2b6e9bb5a0
Create Date: 2026-05-29 08:47:02.592902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e00e10485d0'
down_revision: Union[str, None] = '4e2b6e9bb5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_foreign_key('fk_expenses_created_by_user_id', 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('commission_amount')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_created_by_user_id', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
