"""add manager_approval_pin

Revision ID: 41a1d7bf70e6
Revises: d11023166988
Create Date: 2026-05-21 20:47:13.190286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a1d7bf70e6'
down_revision: Union[str, None] = 'd11023166988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_approval_pin', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.drop_column('manager_approval_pin')

    # ### end Alembic commands ###
