"""add payment methods

Revision ID: 4c21b85a13f5
Revises: 1e1822cb168f
Create Date: 2026-05-26 14:40:02.715948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c21b85a13f5'
down_revision: Union[str, None] = '1e1822cb168f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('google_maps_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('public_slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('manager_approval_pin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashier_discount_limit_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('cashier_discount_limit_value', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('manager_discount_limit_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('manager_discount_limit_value', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('allow_cash', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('allow_vodafone_cash', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('allow_instapay', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('allow_bank_card', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('working_hours', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('landing_hero_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_hero_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_about_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_about_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_hero_badge', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_services_eyebrow', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_services_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_services_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_portfolio_eyebrow', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_portfolio_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_booking_eyebrow', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_booking_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_booking_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_location_eyebrow', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_location_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_location_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_location_open_label', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_location_closed_label', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_location_status_text', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_contact_eyebrow', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_contact_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_contact_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_quick_actions_eyebrow', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_quick_actions_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_quick_actions_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_final_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_final_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_final_button_label', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_hero_highlight_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_hero_highlight_subtitle', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_hero_highlight_badge', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_public_header_badge', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_testimonials_eyebrow', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landing_testimonials_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_testimonials_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landing_cover_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('landing_theme_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('landing_show_staff', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('landing_show_staff_bio', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('landing_stats', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('landing_features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('landing_trust_badges', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('landing_testimonials', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('landing_portfolio', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('social_facebook', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('social_instagram', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('social_tiktok', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('social_youtube', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('public_site_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('public_site_published_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('public_site_published_at')
        batch_op.drop_column('public_site_snapshot')
        batch_op.drop_column('social_youtube')
        batch_op.drop_column('social_tiktok')
        batch_op.drop_column('social_instagram')
        batch_op.drop_column('social_facebook')
        batch_op.drop_column('landing_portfolio')
        batch_op.drop_column('landing_testimonials')
        batch_op.drop_column('landing_trust_badges')
        batch_op.drop_column('landing_features')
        batch_op.drop_column('landing_stats')
        batch_op.drop_column('landing_show_staff_bio')
        batch_op.drop_column('landing_show_staff')
        batch_op.drop_column('landing_theme_id')
        batch_op.drop_column('landing_cover_image_url')
        batch_op.drop_column('landing_testimonials_subtitle')
        batch_op.drop_column('landing_testimonials_title')
        batch_op.drop_column('landing_testimonials_eyebrow')
        batch_op.drop_column('landing_public_header_badge')
        batch_op.drop_column('landing_hero_highlight_badge')
        batch_op.drop_column('landing_hero_highlight_subtitle')
        batch_op.drop_column('landing_hero_highlight_title')
        batch_op.drop_column('landing_final_button_label')
        batch_op.drop_column('landing_final_subtitle')
        batch_op.drop_column('landing_final_title')
        batch_op.drop_column('landing_quick_actions_subtitle')
        batch_op.drop_column('landing_quick_actions_title')
        batch_op.drop_column('landing_quick_actions_eyebrow')
        batch_op.drop_column('landing_contact_subtitle')
        batch_op.drop_column('landing_contact_title')
        batch_op.drop_column('landing_contact_eyebrow')
        batch_op.drop_column('landing_location_status_text')
        batch_op.drop_column('landing_location_closed_label')
        batch_op.drop_column('landing_location_open_label')
        batch_op.drop_column('landing_location_description')
        batch_op.drop_column('landing_location_title')
        batch_op.drop_column('landing_location_eyebrow')
        batch_op.drop_column('landing_booking_subtitle')
        batch_op.drop_column('landing_booking_title')
        batch_op.drop_column('landing_booking_eyebrow')
        batch_op.drop_column('landing_portfolio_title')
        batch_op.drop_column('landing_portfolio_eyebrow')
        batch_op.drop_column('landing_services_subtitle')
        batch_op.drop_column('landing_services_title')
        batch_op.drop_column('landing_services_eyebrow')
        batch_op.drop_column('landing_hero_badge')
        batch_op.drop_column('landing_about_content')
        batch_op.drop_column('landing_about_title')
        batch_op.drop_column('landing_hero_subtitle')
        batch_op.drop_column('landing_hero_title')
        batch_op.drop_column('working_hours')
        batch_op.drop_column('allow_bank_card')
        batch_op.drop_column('allow_instapay')
        batch_op.drop_column('allow_vodafone_cash')
        batch_op.drop_column('allow_cash')
        batch_op.drop_column('manager_discount_limit_value')
        batch_op.drop_column('manager_discount_limit_type')
        batch_op.drop_column('cashier_discount_limit_value')
        batch_op.drop_column('cashier_discount_limit_type')
        batch_op.drop_column('manager_approval_pin')
        batch_op.drop_column('public_slug')
        batch_op.drop_column('google_maps_url')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
