"""add_payroll_logic_and_documents_expiry

Revision ID: 4e2b6e9bb5a0
Revises: acfffcc41c41
Create Date: 2026-05-29 06:56:30.099540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2b6e9bb5a0'
down_revision: Union[str, None] = 'acfffcc41c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_min_attendance_percent', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('enable_attendance_auto_deduction', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('discipline_bonus', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('discipline_bonus')
        batch_op.drop_column('enable_attendance_auto_deduction')
        batch_op.drop_column('bonus_min_attendance_percent')

    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')

    # ### end Alembic commands ###
