"""add_soft_delete_to_customer

Revision ID: 50eec5d4b812
Revises: 0de75d6f3a31
Create Date: 2026-06-10 23:16:10.127271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50eec5d4b812'
down_revision: Union[str, None] = '0de75d6f3a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('booking_source',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['customer_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['voided_by'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('cancellation_count')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('commission_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('offer_products', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_offer_products_id'), ['id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('service_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'barbers', ['barber_id'], ['id'])

    with op.batch_alter_table('service_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'barbers', ['barber_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('offer_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_products_id'))
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'barbers', ['barber_id'], ['id'])

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('commission_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'"),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'approved'"),
               existing_nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'barbers', ['barber_id'], ['id'])
        batch_op.alter_column('booking_source',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'shop'"),
               existing_nullable=True)

    # ### end Alembic commands ###
