"""Add remaining indexes

Revision ID: 66176a4d7061
Revises: 20cd13c54260
Create Date: 2026-05-08 05:37:00.636286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66176a4d7061'
down_revision: Union[str, None] = '20cd13c54260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_shift_id'), ['shift_id'], unique=False)

    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_shifts_cashier_user_id'), ['cashier_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_shifts_cashier_user_id'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_shift_id'))

    # ### end Alembic commands ###
