"""add_cash_transactions_table

Revision ID: 7afda716e6ea
Revises: a2efe8d265b4
Create Date: 2026-05-26 20:22:08.519498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afda716e6ea'
down_revision: Union[str, None] = 'a2efe8d265b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("service_categories"):
        op.create_table(
            "service_categories",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("name_ar", sa.String(length=255), nullable=True),
            sa.Column("icon", sa.String(length=100), nullable=True),
            sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("service_categories", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_service_categories_id"), ["id"], unique=False)

    inspector = sa.inspect(bind)
    service_columns = {column["name"] for column in inspector.get_columns("services")}
    if "category_id" not in service_columns:
        with op.batch_alter_table("services", schema=None) as batch_op:
            batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_no', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transactions_transaction_no'), ['transaction_no'], unique=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        # Check if fk already exists to avoid errors on SQLite
        batch_op.create_foreign_key('fk_services_category', 'service_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('fk_services_category', type_='foreignkey')

    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_transactions_transaction_no'))
        batch_op.drop_index(batch_op.f('ix_cash_transactions_id'))

    op.drop_table('cash_transactions')
    # ### end Alembic commands ###
