"""Add working_hours to business_settings

Revision ID: 82ebc1b6de66
Revises: f1ae0377d66c
Create Date: 2026-05-06 10:08:26.708132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ebc1b6de66'
down_revision: Union[str, None] = 'f1ae0377d66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_settings', sa.Column('working_hours', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_settings', 'working_hours')
    # ### end Alembic commands ###
