"""add_loyalty_fields

Revision ID: 8d5ce9862296
Revises: 7afda716e6ea
Create Date: 2026-05-27 19:52:18.958696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5ce9862296'
down_revision: Union[str, None] = 'c4d8e1f2a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('business_settings', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('loyalty_settings', sa.JSON(), nullable=True))

    # with op.batch_alter_table('customers', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('notes', sa.String(length=1000), nullable=True))
    #     batch_op.add_column(sa.Column('loyalty_points', sa.Numeric(precision=10, scale=2), nullable=False))
    #     batch_op.add_column(sa.Column('lifetime_spend', sa.Numeric(precision=12, scale=2), nullable=False))
    #     batch_op.add_column(sa.Column('current_tier', sa.String(length=50), nullable=False))

    existing_category_fks = {
        foreign_key.get("name")
        for foreign_key in sa.inspect(op.get_bind()).get_foreign_keys("services")
        if foreign_key.get("referred_table") == "service_categories"
    }
    if not existing_category_fks:
        with op.batch_alter_table('services', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_services_category_id', 'service_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('fk_services_category_id', type_='foreignkey')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('current_tier')
        batch_op.drop_column('lifetime_spend')
        batch_op.drop_column('loyalty_points')
        batch_op.drop_column('notes')

    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.drop_column('loyalty_settings')

    # ### end Alembic commands ###
