"""add pos_shift and update invoice_item

Revision ID: a2efe8d265b4
Revises: a61b3a066e00
Create Date: 2026-05-26 17:39:30.418395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2efe8d265b4'
down_revision: Union[str, None] = 'a61b3a066e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_closing_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_closing_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('opening_note', sa.Text(), nullable=True),
    sa.Column('closing_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_shifts_id'), ['id'], unique=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invoice_items_product_id', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_shifts_id'))

    op.drop_table('pos_shifts')
    # ### end Alembic commands ###
