"""initial_clean_baseline

Revision ID: a512a1ff3bfc
Revises: 
Create Date: 2026-05-05 18:57:18.625679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a512a1ff3bfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('bio_ar', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('employment_status', sa.String(length=30), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allow_online_booking', sa.Boolean(), nullable=False),
    sa.Column('allow_walk_in_assignment', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barbers'))
    )
    op.create_index(op.f('ix_barbers_id'), 'barbers', ['id'], unique=False)
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_name', sa.String(length=255), nullable=False),
    sa.Column('shop_phone', sa.String(length=30), nullable=True),
    sa.Column('shop_whatsapp', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('receipt_footer', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('cashier_discount_limit_type', sa.String(length=20), nullable=False),
    sa.Column('cashier_discount_limit_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('manager_discount_limit_type', sa.String(length=20), nullable=False),
    sa.Column('manager_discount_limit_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allow_cash', sa.Boolean(), nullable=False),
    sa.Column('allow_vodafone_cash', sa.Boolean(), nullable=False),
    sa.Column('allow_instapay', sa.Boolean(), nullable=False),
    sa.Column('allow_bank_card', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_settings'))
    )
    op.create_index(op.f('ix_business_settings_id'), 'business_settings', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('phone_normalized', sa.String(length=30), nullable=True),
    sa.Column('preferred_channel', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('offer_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index(op.f('ix_offers_end_date'), 'offers', ['end_date'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_is_active'), 'offers', ['is_active'], unique=False)
    op.create_index(op.f('ix_offers_start_date'), 'offers', ['start_date'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_quantity_alert', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('seo_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=False),
    sa.Column('meta_description_ar', sa.Text(), nullable=True),
    sa.Column('hero_title_ar', sa.String(length=255), nullable=True),
    sa.Column('hero_subtitle_ar', sa.Text(), nullable=True),
    sa.Column('content_ar', sa.Text(), nullable=True),
    sa.Column('faq_json', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_pages'))
    )
    op.create_index(op.f('ix_seo_pages_id'), 'seo_pages', ['id'], unique=False)
    op.create_index(op.f('ix_seo_pages_slug'), 'seo_pages', ['slug'], unique=True)
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories'))
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_table('barber_presence_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_barber_presence_logs_barber_id_barbers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barber_presence_logs'))
    )
    op.create_index(op.f('ix_barber_presence_logs_id'), 'barber_presence_logs', ['id'], unique=False)
    op.create_table('barber_time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('off_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_barber_time_off_barber_id_barbers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barber_time_off'))
    )
    op.create_index(op.f('ix_barber_time_off_id'), 'barber_time_off', ['id'], unique=False)
    op.create_table('barber_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_barber_working_hours_barber_id_barbers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barber_working_hours'))
    )
    op.create_index(op.f('ix_barber_working_hours_id'), 'barber_working_hours', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('description_ar', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_bookable_online', sa.Boolean(), nullable=False),
    sa.Column('is_pos_enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_specific_barber', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_services_category_id_service_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_users_barber_id_barbers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_values_json', sa.Text(), nullable=True),
    sa.Column('new_values_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('inventory_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_inventory_logs_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_logs_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_logs'))
    )
    op.create_index(op.f('ix_inventory_logs_id'), 'inventory_logs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('offer_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_services_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_offer_services_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_services'))
    )
    op.create_index(op.f('ix_offer_services_id'), 'offer_services', ['id'], unique=False)
    op.create_index(op.f('ix_offer_services_offer_id'), 'offer_services', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_services_service_id'), 'offer_services', ['service_id'], unique=False)
    op.create_table('pos_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashier_user_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_commissions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('manager_reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('manager_review_note', sa.Text(), nullable=True),
    sa.Column('denominations_json', sa.Text(), nullable=True),
    sa.Column('discrepancy_note', sa.Text(), nullable=True),
    sa.Column('service_sales_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('product_sales_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expenses_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commissions_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tips_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cashier_user_id'], ['users.id'], name=op.f('fk_pos_shifts_cashier_user_id_users')),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_pos_shifts_closed_by_user_id_users')),
    sa.ForeignKeyConstraint(['manager_reviewed_by_user_id'], ['users.id'], name=op.f('fk_pos_shifts_manager_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], name=op.f('fk_pos_shifts_opened_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pos_shifts'))
    )
    op.create_index(op.f('ix_pos_shifts_id'), 'pos_shifts', ['id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_preferences_user_id'))
    )
    op.create_index(op.f('ix_preferences_id'), 'preferences', ['id'], unique=False)
    op.create_table('service_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_service_products_product_id_products')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_products_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_products'))
    )
    op.create_index(op.f('ix_service_products_id'), 'service_products', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('requested_barber_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmation_channel', sa.String(length=30), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('total_estimated_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('confirmation_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_2h_sent', sa.Boolean(), nullable=False),
    sa.Column('converted_to_session', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_appointments_barber_id_barbers')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_appointments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_appointments_customer_id_customers')),
    sa.ForeignKeyConstraint(['requested_barber_id'], ['barbers.id'], name=op.f('fk_appointments_requested_barber_id_barbers')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_appointments_shift_id_pos_shifts')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_appointments_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index('idx_app_barber_date', 'appointments', ['barber_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_end_at'), 'appointments', ['end_at'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_start_at'), 'appointments', ['start_at'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_expenses_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_expenses_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('appointment_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('service_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_snapshot_minutes', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_changed', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_services_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointment_services_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_services'))
    )
    op.create_index(op.f('ix_appointment_services_id'), 'appointment_services', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('barber_id', sa.Integer(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('discount_reason', sa.Text(), nullable=True),
    sa.Column('discount_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_invoices_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_invoices_barber_id_barbers')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_invoices_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_invoices_customer_id_customers')),
    sa.ForeignKeyConstraint(['discount_approved_by_user_id'], ['users.id'], name=op.f('fk_invoices_discount_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_invoices_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('barber_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_verified_visit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_reviews_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_reviews_barber_id_barbers')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_reviews_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_reviews_appointment_id'))
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('service_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_service_sessions_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_service_sessions_barber_id_barbers')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_service_sessions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_service_sessions_customer_id_customers')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_sessions_service_id_services')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_service_sessions_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_sessions'))
    )
    op.create_index(op.f('ix_service_sessions_id'), 'service_sessions', ['id'], unique=False)
    op.create_table('discount_approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_discount_approval_requests_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_discount_approval_requests_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_discount_approval_requests_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_approval_requests'))
    )
    op.create_index(op.f('ix_discount_approval_requests_id'), 'discount_approval_requests', ['id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('barber_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_invoice_items_barber_id_barbers')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_invoice_items_product_id_products')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_invoice_items_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_table('invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('external_channel', sa.String(length=100), nullable=True),
    sa.Column('received_by_user_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_payments_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], name=op.f('fk_invoice_payments_received_by_user_id_users')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_invoice_payments_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_payments'))
    )
    op.create_index(op.f('ix_invoice_payments_id'), 'invoice_payments', ['id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_phone', sa.String(length=30), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_notification_logs_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_notification_logs_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_notification_logs_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs'))
    )
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.create_table('session_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_session_products_product_id_products')),
    sa.ForeignKeyConstraint(['session_id'], ['service_sessions.id'], name=op.f('fk_session_products_session_id_service_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_products'))
    )
    op.create_index(op.f('ix_session_products_id'), 'session_products', ['id'], unique=False)
    op.create_table('walk_in_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('requested_barber_id', sa.Integer(), nullable=True),
    sa.Column('assigned_barber_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queue_note', sa.Text(), nullable=True),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_session_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_barber_id'], ['barbers.id'], name=op.f('fk_walk_in_queue_assigned_barber_id_barbers')),
    sa.ForeignKeyConstraint(['converted_session_id'], ['service_sessions.id'], name=op.f('fk_walk_in_queue_converted_session_id_service_sessions')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_walk_in_queue_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_walk_in_queue_customer_id_customers')),
    sa.ForeignKeyConstraint(['requested_barber_id'], ['barbers.id'], name=op.f('fk_walk_in_queue_requested_barber_id_barbers')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_walk_in_queue_service_id_services')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_walk_in_queue_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_walk_in_queue'))
    )
    op.create_index(op.f('ix_walk_in_queue_id'), 'walk_in_queue', ['id'], unique=False)
    op.create_index(op.f('ix_walk_in_queue_ticket_no'), 'walk_in_queue', ['ticket_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walk_in_queue_ticket_no'), table_name='walk_in_queue')
    op.drop_index(op.f('ix_walk_in_queue_id'), table_name='walk_in_queue')
    op.drop_table('walk_in_queue')
    op.drop_index(op.f('ix_session_products_id'), table_name='session_products')
    op.drop_table('session_products')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_invoice_payments_id'), table_name='invoice_payments')
    op.drop_table('invoice_payments')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_discount_approval_requests_id'), table_name='discount_approval_requests')
    op.drop_table('discount_approval_requests')
    op.drop_index(op.f('ix_service_sessions_id'), table_name='service_sessions')
    op.drop_table('service_sessions')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_appointment_services_id'), table_name='appointment_services')
    op.drop_table('appointment_services')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_appointments_start_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_end_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_index('idx_app_barber_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_service_products_id'), table_name='service_products')
    op.drop_table('service_products')
    op.drop_index(op.f('ix_preferences_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_pos_shifts_id'), table_name='pos_shifts')
    op.drop_table('pos_shifts')
    op.drop_index(op.f('ix_offer_services_service_id'), table_name='offer_services')
    op.drop_index(op.f('ix_offer_services_offer_id'), table_name='offer_services')
    op.drop_index(op.f('ix_offer_services_id'), table_name='offer_services')
    op.drop_table('offer_services')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inventory_logs_id'), table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_barber_working_hours_id'), table_name='barber_working_hours')
    op.drop_table('barber_working_hours')
    op.drop_index(op.f('ix_barber_time_off_id'), table_name='barber_time_off')
    op.drop_table('barber_time_off')
    op.drop_index(op.f('ix_barber_presence_logs_id'), table_name='barber_presence_logs')
    op.drop_table('barber_presence_logs')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index(op.f('ix_seo_pages_slug'), table_name='seo_pages')
    op.drop_index(op.f('ix_seo_pages_id'), table_name='seo_pages')
    op.drop_table('seo_pages')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_offers_start_date'), table_name='offers')
    op.drop_index(op.f('ix_offers_is_active'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_end_date'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_business_settings_id'), table_name='business_settings')
    op.drop_table('business_settings')
    op.drop_index(op.f('ix_barbers_id'), table_name='barbers')
    op.drop_table('barbers')
    # ### end Alembic commands ###
