"""add_product_weight_and_expense_fields

Revision ID: c8ba0291a033
Revises: 41a1d7bf70e6
Create Date: 2026-05-22 05:25:44.585421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ba0291a033'
down_revision: Union[str, None] = '41a1d7bf70e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_advance', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_expenses_employee_id_employees'), 'employees', ['employee_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('weight')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_expenses_employee_id_employees'), type_='foreignkey')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('is_advance')
        batch_op.drop_column('invoice_image_url')

    # ### end Alembic commands ###
