"""init all tables

Revision ID: d11023166988
Revises: 
Create Date: 2026-05-20 03:13:32.697307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11023166988'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_name', sa.String(length=255), nullable=False),
    sa.Column('shop_phone', sa.String(length=30), nullable=True),
    sa.Column('shop_whatsapp', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('google_maps_url', sa.String(length=1000), nullable=True),
    sa.Column('receipt_footer', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('public_slug', sa.String(length=255), nullable=True),
    sa.Column('cashier_discount_limit_type', sa.String(length=20), nullable=False),
    sa.Column('cashier_discount_limit_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('manager_discount_limit_type', sa.String(length=20), nullable=False),
    sa.Column('manager_discount_limit_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allow_cash', sa.Boolean(), nullable=False),
    sa.Column('allow_vodafone_cash', sa.Boolean(), nullable=False),
    sa.Column('allow_instapay', sa.Boolean(), nullable=False),
    sa.Column('allow_bank_card', sa.Boolean(), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('landing_hero_title', sa.String(length=500), nullable=True),
    sa.Column('landing_hero_subtitle', sa.Text(), nullable=True),
    sa.Column('landing_about_title', sa.String(length=500), nullable=True),
    sa.Column('landing_about_content', sa.Text(), nullable=True),
    sa.Column('landing_hero_badge', sa.String(length=255), nullable=True),
    sa.Column('landing_services_eyebrow', sa.String(length=255), nullable=True),
    sa.Column('landing_services_title', sa.String(length=500), nullable=True),
    sa.Column('landing_services_subtitle', sa.Text(), nullable=True),
    sa.Column('landing_portfolio_eyebrow', sa.String(length=255), nullable=True),
    sa.Column('landing_portfolio_title', sa.String(length=500), nullable=True),
    sa.Column('landing_booking_eyebrow', sa.String(length=255), nullable=True),
    sa.Column('landing_booking_title', sa.String(length=500), nullable=True),
    sa.Column('landing_booking_subtitle', sa.Text(), nullable=True),
    sa.Column('landing_location_eyebrow', sa.String(length=255), nullable=True),
    sa.Column('landing_location_title', sa.String(length=500), nullable=True),
    sa.Column('landing_location_description', sa.Text(), nullable=True),
    sa.Column('landing_location_open_label', sa.String(length=255), nullable=True),
    sa.Column('landing_location_closed_label', sa.String(length=255), nullable=True),
    sa.Column('landing_location_status_text', sa.String(length=500), nullable=True),
    sa.Column('landing_contact_eyebrow', sa.String(length=255), nullable=True),
    sa.Column('landing_contact_title', sa.String(length=500), nullable=True),
    sa.Column('landing_contact_subtitle', sa.Text(), nullable=True),
    sa.Column('landing_quick_actions_eyebrow', sa.String(length=255), nullable=True),
    sa.Column('landing_quick_actions_title', sa.String(length=500), nullable=True),
    sa.Column('landing_quick_actions_subtitle', sa.Text(), nullable=True),
    sa.Column('landing_final_title', sa.String(length=500), nullable=True),
    sa.Column('landing_final_subtitle', sa.Text(), nullable=True),
    sa.Column('landing_final_button_label', sa.String(length=255), nullable=True),
    sa.Column('landing_hero_highlight_title', sa.String(length=255), nullable=True),
    sa.Column('landing_hero_highlight_subtitle', sa.String(length=500), nullable=True),
    sa.Column('landing_hero_highlight_badge', sa.String(length=255), nullable=True),
    sa.Column('landing_public_header_badge', sa.String(length=255), nullable=True),
    sa.Column('landing_testimonials_eyebrow', sa.String(length=255), nullable=True),
    sa.Column('landing_testimonials_title', sa.String(length=500), nullable=True),
    sa.Column('landing_testimonials_subtitle', sa.Text(), nullable=True),
    sa.Column('landing_cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('landing_theme_id', sa.String(length=50), nullable=True),
    sa.Column('landing_show_staff', sa.Boolean(), nullable=True),
    sa.Column('landing_show_staff_bio', sa.Boolean(), nullable=True),
    sa.Column('landing_stats', sa.JSON(), nullable=True),
    sa.Column('landing_features', sa.JSON(), nullable=True),
    sa.Column('landing_trust_badges', sa.JSON(), nullable=True),
    sa.Column('landing_testimonials', sa.JSON(), nullable=True),
    sa.Column('landing_portfolio', sa.JSON(), nullable=True),
    sa.Column('social_facebook', sa.String(length=500), nullable=True),
    sa.Column('social_instagram', sa.String(length=500), nullable=True),
    sa.Column('social_tiktok', sa.String(length=500), nullable=True),
    sa.Column('social_youtube', sa.String(length=500), nullable=True),
    sa.Column('public_site_snapshot', sa.JSON(), nullable=True),
    sa.Column('public_site_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_settings'))
    )
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_settings_id'), ['id'], unique=False)

    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('phone_normalized', sa.String(length=30), nullable=True),
    sa.Column('preferred_channel', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=True)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('phone_primary', sa.String(length=30), nullable=False),
    sa.Column('phone_secondary', sa.String(length=30), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('governorate', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('detailed_address', sa.Text(), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('bio_ar', sa.Text(), nullable=True),
    sa.Column('bio_en', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('hire_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('work_days_json', sa.JSON(), nullable=True),
    sa.Column('work_hours_json', sa.JSON(), nullable=True),
    sa.Column('show_in_pos', sa.Boolean(), nullable=False),
    sa.Column('show_in_booking', sa.Boolean(), nullable=False),
    sa.Column('allow_online_booking', sa.Boolean(), nullable=False),
    sa.Column('allow_walk_in_assignment', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('default_deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('wallet_number', sa.String(length=30), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('assistant_of_barber_id', sa.Integer(), nullable=True),
    sa.Column('assistant_tasks_json', sa.JSON(), nullable=True),
    sa.Column('receives_commission', sa.Boolean(), nullable=False),
    sa.Column('assistant_commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('has_login_account', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_of_barber_id'], ['employees.id'], name=op.f('fk_employees_assistant_of_barber_id_employees')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('description_ar', sa.String(length=1000), nullable=True),
    sa.Column('description_en', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('offer_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_start_date'), ['start_date'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_quantity_alert', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    op.create_table('seo_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=False),
    sa.Column('meta_description_ar', sa.Text(), nullable=True),
    sa.Column('hero_title_ar', sa.String(length=255), nullable=True),
    sa.Column('hero_subtitle_ar', sa.Text(), nullable=True),
    sa.Column('content_ar', sa.Text(), nullable=True),
    sa.Column('faq_json', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_pages'))
    )
    with op.batch_alter_table('seo_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_pages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_pages_slug'), ['slug'], unique=True)

    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories'))
    )
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_categories_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_users_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_values_json', sa.Text(), nullable=True),
    sa.Column('new_values_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)

    op.create_table('employee_presence_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_presence_logs_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_presence_logs'))
    )
    with op.batch_alter_table('employee_presence_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_presence_logs_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_presence_logs_id'), ['id'], unique=False)

    op.create_table('employee_time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('off_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_time_off_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_time_off'))
    )
    with op.batch_alter_table('employee_time_off', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_time_off_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_time_off_id'), ['id'], unique=False)

    op.create_table('employee_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_working_hours_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_working_hours'))
    )
    with op.batch_alter_table('employee_working_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_working_hours_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_working_hours_id'), ['id'], unique=False)

    op.create_table('inventory_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_inventory_logs_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_logs_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_logs'))
    )
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_logs_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('pos_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashier_user_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_commissions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('manager_reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('manager_review_note', sa.Text(), nullable=True),
    sa.Column('denominations_json', sa.Text(), nullable=True),
    sa.Column('discrepancy_note', sa.Text(), nullable=True),
    sa.Column('service_sales_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('product_sales_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expenses_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commissions_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tips_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cashier_user_id'], ['users.id'], name=op.f('fk_pos_shifts_cashier_user_id_users')),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_pos_shifts_closed_by_user_id_users')),
    sa.ForeignKeyConstraint(['manager_reviewed_by_user_id'], ['users.id'], name=op.f('fk_pos_shifts_manager_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], name=op.f('fk_pos_shifts_opened_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pos_shifts'))
    )
    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_shifts_cashier_user_id'), ['cashier_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_shifts_id'), ['id'], unique=False)

    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_preferences_user_id'))
    )
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preferences_id'), ['id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('description_ar', sa.String(length=1000), nullable=True),
    sa.Column('description_en', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_bookable_online', sa.Boolean(), nullable=False),
    sa.Column('is_pos_enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_specific_barber', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_services_category_id_service_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('requested_employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmation_channel', sa.String(length=30), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('total_estimated_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('confirmation_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_2h_sent', sa.Boolean(), nullable=False),
    sa.Column('converted_to_session', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_appointments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_appointments_customer_id_customers')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_appointments_employee_id_employees')),
    sa.ForeignKeyConstraint(['requested_employee_id'], ['employees.id'], name=op.f('fk_appointments_requested_employee_id_employees')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_appointments_shift_id_pos_shifts')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_appointments_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('idx_app_employee_date', ['employee_id', 'appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_appointment_date'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_requested_employee_id'), ['requested_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_start_at'), ['start_at'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('expense_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_expenses_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_expenses_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_shift_id'), ['shift_id'], unique=False)

    op.create_table('offer_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_services_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_offer_services_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_services'))
    )
    with op.batch_alter_table('offer_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_services_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_services_service_id'), ['service_id'], unique=False)

    op.create_table('service_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_service_products_product_id_products')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_products_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_products'))
    )
    with op.batch_alter_table('service_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_products_id'), ['id'], unique=False)

    op.create_table('appointment_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('service_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_snapshot_minutes', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_changed', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_services_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointment_services_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_services'))
    )
    with op.batch_alter_table('appointment_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_services_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_services_id'), ['id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('discount_reason', sa.Text(), nullable=True),
    sa.Column('discount_approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_invoices_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_invoices_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_invoices_customer_id_customers')),
    sa.ForeignKeyConstraint(['discount_approved_by_user_id'], ['users.id'], name=op.f('fk_invoices_discount_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_invoices_employee_id_employees')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_invoices_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_shift_id'), ['shift_id'], unique=False)

    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('role_snapshot', sa.String(length=100), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payroll_records_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_records_employee_id_employees')),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_payroll_records_expense_id_expenses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payroll_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_records')),
    sa.UniqueConstraint('employee_id', 'period_month', 'period_year', name='_employee_month_year_uc')
    )
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_records_id'), ['id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_verified_visit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_reviews_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_reviews_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_reviews_appointment_id'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)

    op.create_table('service_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_service_sessions_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_service_sessions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_service_sessions_customer_id_customers')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_service_sessions_employee_id_employees')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_sessions_service_id_services')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_service_sessions_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_sessions'))
    )
    with op.batch_alter_table('service_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_sessions_id'), ['id'], unique=False)

    op.create_table('discount_approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_discount_approval_requests_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_discount_approval_requests_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_discount_approval_requests_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_approval_requests'))
    )
    with op.batch_alter_table('discount_approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discount_approval_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discount_approval_requests_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('invoice_adjustment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('requested_values', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_invoice_adjustment_requests_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_adjustment_requests_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_invoice_adjustment_requests_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_adjustment_requests'))
    )
    with op.batch_alter_table('invoice_adjustment_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_adjustment_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_adjustment_requests_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_invoice_items_employee_id_employees')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_invoice_items_product_id_products')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_invoice_items_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('external_channel', sa.String(length=100), nullable=True),
    sa.Column('received_by_user_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_payments_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], name=op.f('fk_invoice_payments_received_by_user_id_users')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_invoice_payments_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_payments'))
    )
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_payments_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_phone', sa.String(length=30), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_notification_logs_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_notification_logs_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_notification_logs_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs'))
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('salary_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('advance_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deducted', sa.Boolean(), nullable=False),
    sa.Column('payroll_record_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_salary_advances_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_salary_advances_employee_id_employees')),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], name=op.f('fk_salary_advances_payroll_record_id_payroll_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_advances'))
    )
    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_advances_id'), ['id'], unique=False)

    op.create_table('session_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_session_products_product_id_products')),
    sa.ForeignKeyConstraint(['session_id'], ['service_sessions.id'], name=op.f('fk_session_products_session_id_service_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_products'))
    )
    with op.batch_alter_table('session_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_products_session_id'), ['session_id'], unique=False)

    op.create_table('walk_in_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('requested_employee_id', sa.Integer(), nullable=True),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queue_note', sa.Text(), nullable=True),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_session_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], name=op.f('fk_walk_in_queue_assigned_employee_id_employees')),
    sa.ForeignKeyConstraint(['converted_session_id'], ['service_sessions.id'], name=op.f('fk_walk_in_queue_converted_session_id_service_sessions')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_walk_in_queue_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_walk_in_queue_customer_id_customers')),
    sa.ForeignKeyConstraint(['requested_employee_id'], ['employees.id'], name=op.f('fk_walk_in_queue_requested_employee_id_employees')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_walk_in_queue_service_id_services')),
    sa.ForeignKeyConstraint(['shift_id'], ['pos_shifts.id'], name=op.f('fk_walk_in_queue_shift_id_pos_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_walk_in_queue'))
    )
    with op.batch_alter_table('walk_in_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_walk_in_queue_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_walk_in_queue_ticket_no'), ['ticket_no'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walk_in_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_walk_in_queue_ticket_no'))
        batch_op.drop_index(batch_op.f('ix_walk_in_queue_id'))

    op.drop_table('walk_in_queue')
    with op.batch_alter_table('session_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_products_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_products_id'))

    op.drop_table('session_products')
    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_advances_id'))

    op.drop_table('salary_advances')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_appointment_id'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_payments_id'))

    op.drop_table('invoice_payments')
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_items_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('invoice_adjustment_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_adjustment_requests_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_adjustment_requests_id'))

    op.drop_table('invoice_adjustment_requests')
    with op.batch_alter_table('discount_approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discount_approval_requests_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_discount_approval_requests_id'))

    op.drop_table('discount_approval_requests')
    with op.batch_alter_table('service_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_sessions_id'))

    op.drop_table('service_sessions')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_records_id'))

    op.drop_table('payroll_records')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_shift_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_employee_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_appointment_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('appointment_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_services_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_services_appointment_id'))

    op.drop_table('appointment_services')
    with op.batch_alter_table('service_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_products_id'))

    op.drop_table('service_products')
    with op.batch_alter_table('offer_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_services_service_id'))
        batch_op.drop_index(batch_op.f('ix_offer_services_offer_id'))
        batch_op.drop_index(batch_op.f('ix_offer_services_id'))

    op.drop_table('offer_services')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_shift_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_start_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_shift_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_requested_employee_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_end_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_employee_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_date'))
        batch_op.drop_index('idx_app_employee_date')

    op.drop_table('appointments')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_id'))
        batch_op.drop_index(batch_op.f('ix_services_category_id'))

    op.drop_table('services')
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preferences_id'))

    op.drop_table('preferences')
    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_shifts_id'))
        batch_op.drop_index(batch_op.f('ix_pos_shifts_cashier_user_id'))

    op.drop_table('pos_shifts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_logs_id'))

    op.drop_table('inventory_logs')
    with op.batch_alter_table('employee_working_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_working_hours_id'))
        batch_op.drop_index(batch_op.f('ix_employee_working_hours_employee_id'))

    op.drop_table('employee_working_hours')
    with op.batch_alter_table('employee_time_off', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_time_off_id'))
        batch_op.drop_index(batch_op.f('ix_employee_time_off_employee_id'))

    op.drop_table('employee_time_off')
    with op.batch_alter_table('employee_presence_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_presence_logs_id'))
        batch_op.drop_index(batch_op.f('ix_employee_presence_logs_employee_id'))

    op.drop_table('employee_presence_logs')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_categories_id'))

    op.drop_table('service_categories')
    with op.batch_alter_table('seo_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_seo_pages_id'))

    op.drop_table('seo_pages')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))

    op.drop_table('products')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_start_date'))
        batch_op.drop_index(batch_op.f('ix_offers_is_active'))
        batch_op.drop_index(batch_op.f('ix_offers_id'))
        batch_op.drop_index(batch_op.f('ix_offers_end_date'))

    op.drop_table('offers')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_id'))

    op.drop_table('employees')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_id'))

    op.drop_table('customers')
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_settings_id'))

    op.drop_table('business_settings')
    # ### end Alembic commands ###
