"""add_deleted_by_and_archive_reason_to_customer

Revision ID: da028f4275cb
Revises: dd86889d3d74
Create Date: 2026-08-07 12:52:44.324708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da028f4275cb'
down_revision: Union[str, None] = 'dd86889d3d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archive_reason', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key('fk_customers_deleted_by_user', 'users', ['deleted_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_deleted_by_user', type_='foreignkey')
        batch_op.drop_column('archive_reason')
        batch_op.drop_column('deleted_by_user_id')
    # ### end Alembic commands ###