"""Apply database cleanup cascades and indexes

Revision ID: dae81f1cceae
Revises: 82ebc1b6de66
Create Date: 2026-05-08 05:35:24.311752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae81f1cceae'
down_revision: Union[str, None] = '82ebc1b6de66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_services', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointment_services_appointment_id_appointments', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_appointment_services_appointment_id_appointments'), 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_barber_id'), ['barber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_requested_barber_id'), ['requested_barber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_shift_id'), ['shift_id'], unique=False)

    with op.batch_alter_table('barber_presence_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barber_presence_logs_barber_id'), ['barber_id'], unique=False)
        batch_op.drop_constraint('fk_barber_presence_logs_barber_id_barbers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_barber_presence_logs_barber_id_barbers'), 'barbers', ['barber_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('barber_time_off', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barber_time_off_barber_id'), ['barber_id'], unique=False)
        batch_op.drop_constraint('fk_barber_time_off_barber_id_barbers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_barber_time_off_barber_id_barbers'), 'barbers', ['barber_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('barber_working_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barber_working_hours_barber_id'), ['barber_id'], unique=False)
        batch_op.drop_constraint('fk_barber_working_hours_barber_id_barbers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_barber_working_hours_barber_id_barbers'), 'barbers', ['barber_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('discount_approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discount_approval_requests_invoice_id'), ['invoice_id'], unique=False)
        batch_op.drop_constraint('fk_discount_approval_requests_invoice_id_invoices', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_discount_approval_requests_invoice_id_invoices'), 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.drop_constraint('fk_invoice_items_invoice_id_invoices', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_invoice_items_invoice_id_invoices'), 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.drop_constraint('fk_invoice_payments_invoice_id_invoices', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_invoice_payments_invoice_id_invoices'), 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_barber_id'), ['barber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_shift_id'), ['shift_id'], unique=False)

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_invoice_id'), ['invoice_id'], unique=False)
        batch_op.drop_constraint('fk_notification_logs_appointment_id_appointments', type_='foreignkey')
        batch_op.drop_constraint('fk_notification_logs_invoice_id_invoices', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notification_logs_invoice_id_invoices'), 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_notification_logs_appointment_id_appointments'), 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('session_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_products_session_id'), ['session_id'], unique=False)
        batch_op.drop_constraint('fk_session_products_session_id_service_sessions', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_session_products_session_id_service_sessions'), 'service_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_session_products_session_id_service_sessions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_session_products_session_id_service_sessions', 'service_sessions', ['session_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_session_products_session_id'))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notification_logs_appointment_id_appointments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notification_logs_invoice_id_invoices'), type_='foreignkey')
        batch_op.create_foreign_key('fk_notification_logs_invoice_id_invoices', 'invoices', ['invoice_id'], ['id'])
        batch_op.create_foreign_key('fk_notification_logs_appointment_id_appointments', 'appointments', ['appointment_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_notification_logs_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_appointment_id'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_shift_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_barber_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_appointment_id'))

    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invoice_payments_invoice_id_invoices'), type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_payments_invoice_id_invoices', 'invoices', ['invoice_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_invoice_payments_invoice_id'))

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invoice_items_invoice_id_invoices'), type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_items_invoice_id_invoices', 'invoices', ['invoice_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))

    with op.batch_alter_table('discount_approval_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_discount_approval_requests_invoice_id_invoices'), type_='foreignkey')
        batch_op.create_foreign_key('fk_discount_approval_requests_invoice_id_invoices', 'invoices', ['invoice_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_discount_approval_requests_invoice_id'))

    with op.batch_alter_table('barber_working_hours', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_barber_working_hours_barber_id_barbers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_barber_working_hours_barber_id_barbers', 'barbers', ['barber_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_barber_working_hours_barber_id'))

    with op.batch_alter_table('barber_time_off', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_barber_time_off_barber_id_barbers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_barber_time_off_barber_id_barbers', 'barbers', ['barber_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_barber_time_off_barber_id'))

    with op.batch_alter_table('barber_presence_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_barber_presence_logs_barber_id_barbers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_barber_presence_logs_barber_id_barbers', 'barbers', ['barber_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_barber_presence_logs_barber_id'))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_shift_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_requested_barber_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_barber_id'))

    with op.batch_alter_table('appointment_services', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointment_services_appointment_id_appointments'), type_='foreignkey')
        batch_op.create_foreign_key('fk_appointment_services_appointment_id_appointments', 'appointments', ['appointment_id'], ['id'])

    # ### end Alembic commands ###
