"""Add payroll and update expenses

Revision ID: f1ae0377d66c
Revises: a512a1ff3bfc
Create Date: 2026-05-06 09:12:48.540831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ae0377d66c'
down_revision: Union[str, None] = 'a512a1ff3bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('barber_id', sa.Integer(), nullable=True),
    sa.Column('employee_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('role_snapshot', sa.String(length=100), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_payroll_records_barber_id_barbers')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payroll_records_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_payroll_records_employee_id_users')),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_payroll_records_expense_id_expenses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_records')),
    sa.UniqueConstraint('employee_id', 'period_month', 'period_year', name='_employee_month_year_uc')
    )
    op.create_index(op.f('ix_payroll_records_id'), 'payroll_records', ['id'], unique=False)
    op.add_column('expenses', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('payment_method', sa.String(length=50), nullable=False))
    op.add_column('expenses', sa.Column('expense_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('expenses', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('expenses', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('reason', sa.TEXT(), nullable=True))
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'status')
    op.drop_column('expenses', 'expense_date')
    op.drop_column('expenses', 'payment_method')
    op.drop_column('expenses', 'description')
    op.drop_column('expenses', 'title')
    op.drop_index(op.f('ix_payroll_records_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    # ### end Alembic commands ###
